# Generated by Django 4.2.3 on 2023-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Признак активации'),
        ),
        migrations.AddField(
            model_name='users',
            name='mytoken',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='токен'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
