# Generated by Django 4.2.3 on 2023-07-19 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<function now at 0x7f020c29ba60>', max_length=63, verbose_name='Название')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней попытки')),
                ('status', models.CharField(max_length=25, verbose_name='Статус попытки')),
                ('answer', models.TextField(default=None, max_length=511, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-date_last'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=63, verbose_name='Тема письма')),
                ('body', models.TextField(max_length=511, verbose_name='Содержимое письма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['theme'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=127, verbose_name='Название')),
                ('date_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки')),
                ('date_end_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('periodicity', models.CharField(choices=[('Раз в минуту', 'Раз в минуту'), ('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=63, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Создана', max_length=63, verbose_name='Статус рассылки')),
                ('client_name', models.ManyToManyField(to='servises.client', verbose_name='Имя клиентов')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
