# Generated by Django 4.2.3 on 2023-07-13 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0002_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=127, verbose_name='Название')),
                ('date_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки')),
                ('date_end_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания рассылки')),
                ('periodicity', models.CharField(choices=[('1', 'Раз день'), ('2', 'Раз в неделю'), ('3', 'Раз в месяц')], default='1', max_length=63, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('1', 'Создана'), ('2', 'Активна'), ('3', 'Завершена')], default='3', max_length=63, verbose_name='Статус рассылки')),
                ('client_name', models.ManyToManyField(to='servises.client', verbose_name='Имя клиентов')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
