# Generated by Django 4.2.3 on 2023-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_alter_client_creator_alter_logs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7efd8a383a60>', max_length=63, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Активирована', 'Активирована'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Создана', max_length=63, verbose_name='Статус рассылки'),
        ),
    ]
