# Generated by Django 4.2.3 on 2023-07-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_settings_is_active_alter_settings_periodicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=63, verbose_name='Тема письма')),
                ('body', models.TextField(max_length=511, verbose_name='Содержимое письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['theme'],
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servises.messages', verbose_name='Письмо для рассылки'),
        ),
    ]
