# Generated by Django 4.2.3 on 2023-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0005_alter_logs_title_alter_settings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f28f955ba60>', max_length=63, verbose_name='Название'),
        ),
    ]
