# Generated by Django 4.2.3 on 2023-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0005_messages_settings_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней попытки')),
                ('status', models.CharField(max_length=25, verbose_name='Статус попытки')),
                ('answer', models.TextField(default=None, max_length=511, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
