# Generated by Django 4.2.3 on 2023-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0006_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7ff8e1ce3a60>', max_length=63, verbose_name='Название'),
        ),
    ]
