# Generated by Django 4.2.3 on 2023-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0007_logs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f96b795ba60>', max_length=63, verbose_name='Название'),
        ),
    ]
