# Generated by Django 4.2.3 on 2023-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0008_logs_is_active_alter_logs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='is_active',
        ),
        migrations.AddField(
            model_name='messages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f98c771ba60>', max_length=63, verbose_name='Название'),
        ),
    ]
