# Generated by Django 4.2.3 on 2023-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0009_remove_logs_is_active_messages_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f0703b03a60>', max_length=63, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Создана', max_length=63, verbose_name='Статус рассылки'),
        ),
    ]
