# Generated by Django 4.2.3 on 2023-07-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0010_alter_logs_title_alter_settings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.settings', verbose_name='Настройка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7fca4b8e3a60>', max_length=63, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='periodicity',
            field=models.CharField(choices=[('Раз в минуту', 'Раз в минуту'), ('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=63, verbose_name='Периодичность рассылки'),
        ),
    ]
