# Generated by Django 4.2.3 on 2023-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0011_logs_settings_alter_logs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7f4c5eef7a60>', max_length=63, verbose_name='Название'),
        ),
    ]
