# Generated by Django 4.2.3 on 2023-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0012_alter_logs_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-date_last'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='title',
            field=models.CharField(default='<function now at 0x7fd7ccbf7a60>', max_length=63, verbose_name='Название'),
        ),
    ]
